### PR TITLE
Add ability to set single operator-namespace for the controller to watch

### PR DESCRIPTION
**Pull request by ryan-scheinberg**
I have been experiencing slowness with too many composable objects across namespaces.  Increasing resources and concurrency did not help.  I switched to namespaced deployments of the controller with one cluster-wide deployment of the crd's.  This cut reconcile time, which has been about proportional to the number of objects.  

Is this a useful addition to the code?  I am hoping to get off my fork for future updates.  Please let me know if there are other steps I need to follow for a PR / if I should share any tests.  Thanks!

### CODE REVIEW

**Comment by xvzf** [comment]
Your test-case failing is just a flaky one (linked to timeouts), if you like to feel free to rebase on #97

**Comment by ryan-scheinberg** [comment]
I have rebased off of the v3 migration branch.  I suppose I will leave this pull request open for after #97 is merged?

**Comment by ryan-scheinberg** [comment]
For my tests, sdk/ had to be in Dockerfile for the image to build, and the cert associated with the webhook was failing on startup.  Did not seem to matter what I removed from my deploy yaml.  If builds are succeeding for others on the v3 migration pr, then I can make another branch with just the namespaced change if that is a useful addition.

**Comment by xvzf** [comment]
Hey @ryan-scheinberg , it's fixed in our fork (@ankorstore); if you want to create a PR there, my PR won't be merged thus this operator will not be compatible with k8s >= 1.22

**Comment by xvzf** [comment]
Hey @ryan-scheinberg, now that this project has a new home - would you mind updating your PR? :)

**Comment by xvzf** [comment]
I'll close this for now. Feel free to re-open it @ryan-scheinberg

**Pull request closed without merging**
